name: i_am_a_student
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rich_alert: ^0.1.32
  giffy_dialog: ^1.6.1
  fancy_dialog: ^1.0.1
  flutter_webview_plugin: ^0.3.10+1
  connectivity: ^0.4.6+2
  rflutter_alert: ^1.0.2
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.0.3
  http: ^0.12.0
  cached_network_image: ^2.0.0
  material_search: ^0.2.8
  datetime_picker_formfield: ^0.1.7
  smooth_star_rating: 1.0.1
  image_picker: ^0.6.2+2
  file_picker: ^1.1.1
  date_format: ^1.0.6
  share: ^0.6.0+1
  package_info: ^0.4.0+2
  flutter_slidable: ^0.4.9
  url_launcher: ^5.0.1
  flutter_markdown: ^0.2.0
  html: any
  dio: any
  launch_review: ^2.0.0
  webview_flutter: ^0.3.14+1
  path_provider: any
  flutter_html: ^0.8.2
  flutter_image_compress: ^0.6.3
  image: ^2.1.4
  flutter_responsive_screen: ^1.0.0
  flutter_spinkit: ^3.1.0
  avatar_glow: ^0.2.0
  lazy_load_scrollview: ^0.0.3
  photo_view: ^0.4.2
  zefyr: ^0.7.0
  open_file: ^2.1.1
  smart_flare: ^0.2.8
  after_layout: ^1.0.7+2
  flutter_full_pdf_viewer: ^1.0.6



dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"

flutter:

  uses-material-design: true

  assets:
  - images/no_internet.png
  - images/google.png
  - images/facebook.png
  - images/login.png
  - images/registration.png
  - images/verification.png
  - images/key.png
  - images/user.png
  - images/notdatafound.png
  - images/qustion.png
  - images/keyhole.png
  - images/clearfilter.png
  - images/logo.png
  - images/bg.jpeg
  - images/Verify.png
  - images/Verified.png
  - images/nopicon.png
  - images/bg2.jpeg
  - images/ele.gif
  - images/logout.png
  - images/sort.png
  - images/filter_white.png
  - images/listview.png
  - images/gridview.png
  - images/steper_for_address_screen.png
  - images/emptycart.png
  - images/placeholder.png
  - images/addressStepper.png
  - images/cartprocess2.png
  - images/cartprocess3.png
  - images/confirmorder.png
  - images/rewardpiont.png
  - images/orderconfirm.jpeg
  - images/Contact_Us.png
  - images/emailsend.png
  - images/noimage.png
  - images/nowishlist.png
  - images/no_orders.png
  - images/noaddress.png
  - images/downloadproduct.png
  - images/noreview.png
  - images/stepper1.png
  - images/stepper2.png
  - images/stepper3.png
  - images/stepper4.png
  - images/payment/paybg.jpg
  - images/payment/bg2.jpg
  - images/payment/net_banking.png
  - images/payment/cashcard.png
  - images/payment/craditcard.png
  - images/payment/dabitcard.png
  - images/payment/emi.png
  - images/payment/neft.png
  - images/payment/net_banking.png
  - images/payment/tez.png
  - images/payment/upi.png
  - images/payment/wallet.png

  fonts:
  - family: EncodeSans
    fonts:
    - asset: font/Rubik-Medium.ttf
    - asset: font/Rubik-Regular.ttf
    - asset: font/EncodeSans-Black.ttf
    - asset: font/EncodeSans-Bold.ttf
    - asset: font/EncodeSans-ExtraBold.ttf
    - asset: font/EncodeSans-ExtraLight.ttf
    - asset: font/EncodeSans-Light.ttf
    - asset: font/EncodeSans-Medium.ttf
    - asset: font/EncodeSans-Regular.ttf
    - asset: font/EncodeSans-SemiBold.ttf
    - asset: font/EncodeSans-Thin.ttf

  # An image asset can refer to one or more resolution-specific " variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-pafilter_filledckages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
